name: Build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - '2.1'
          - '2.2'
          - '3.1'
    name: .NET ${{ matrix.dotnet-version }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet restore
      - env:
          DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
        run: dotnet test
